spring:
  datasource:
    url: jdbc:mysql://172.26.234.34:3306/pdms?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: 123456
    hikari:
      pool-name: user-hikari




